modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License"
[[mods]]
  modId="skillsreborn"
  version="${file.jarVersion}"
  displayName="SkillsReborn"
  credits="Buuz135, Vazkii & Wii"
  authors="OneLousyGamer"
  description='''SkillsReborn is a continuation of Reskillable. SkillsReborn is a mod about leveling various skills up, using XP. Leveling skills up allow you to unlock traits and use more items. By default, a lot of vanilla items are locked to require leveling your skills up. For example, you're not allowed to use a Diamond Pickaxe until you reach level 16 Mining.'''
[[dependencies.skillsreborn]]
  modId="forge"
  mandatory=true
  versionRange="[36,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.skillsreborn]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.5,1.17)"
  ordering="NONE"
  side="BOTH"
